package com.songtaoluo.battlecity.game

import com.songtaoluo.battlecity.model.Faction
import com.songtaoluo.battlecity.model.VehicleId
import com.songtaoluo.battlecity.model.VehicleRole
import com.songtaoluo.battlecity.model.VehicleSpec

object VehicleCatalog {
    val all: List<VehicleSpec> = listOf(
        VehicleSpec(
            id = VehicleId.PZ_IV_H,
            faction = Faction.GERMAN,
            role = VehicleRole.MEDIUM,
            displayName = "四号H型中型坦克",
            shortName = "四号H型",
            history = "德军装甲部队的可靠主力，火力、机动和防护均衡，适合作为库尔斯克进攻线的初始车辆。",
            price = 0,
            speed = 118f,
            hp = 3,
            reloadMs = 620,
            bulletSpeed = 345f,
            bulletPower = 2,
            penetration = 78,
            armorFront = 80,
            armorSide = 45,
            armorRear = 30,
            visionRange = 160f,
            scoutReveal = false,
            bodyColor = "#7D7A68",
            darkColor = "#3C3B33",
            trimColor = "#D8D0A8",
        ),
        VehicleSpec(
            id = VehicleId.PZ_III,
            faction = Faction.GERMAN,
            role = VehicleRole.MEDIUM,
            displayName = "三号L型中型坦克",
            shortName = "三号L型",
            history = "斯大林格勒时期的德军城市战主力，机动灵活、适合巷战近距离交火，但火力和防护不及四号，遭遇T-34往往处于劣势。",
            price = 460,
            speed = 134f,
            hp = 3,
            reloadMs = 560,
            bulletSpeed = 325f,
            bulletPower = 2,
            penetration = 65,
            armorFront = 57,
            armorSide = 35,
            armorRear = 25,
            visionRange = 172f,
            scoutReveal = false,
            bodyColor = "#6B6858",
            darkColor = "#343328",
            trimColor = "#CEC8B0",
        ),
        VehicleSpec(
            id = VehicleId.TIGER_I,
            faction = Faction.GERMAN,
            role = VehicleRole.HEAVY,
            displayName = "虎式I型重型坦克",
            shortName = "虎式I型",
            history = "高防护、高火力的重型突破车辆。正面压制能力强，但转场速度慢，容易被轻型单位绕侧。",
            price = 900,
            speed = 82f,
            hp = 5,
            reloadMs = 820,
            bulletSpeed = 390f,
            bulletPower = 3,
            penetration = 112,
            armorFront = 125,
            armorSide = 82,
            armorRear = 55,
            visionRange = 150f,
            scoutReveal = false,
            bodyColor = "#9C8A5D",
            darkColor = "#4C432D",
            trimColor = "#F2D88B",
        ),
        VehicleSpec(
            id = VehicleId.FERDINAND,
            faction = Faction.GERMAN,
            role = VehicleRole.TANK_DESTROYER,
            displayName = "费迪南坦克歼击车",
            shortName = "费迪南",
            history = "无炮塔重型歼击车，正面装甲极高，长炮管炮弹速度快；侧后防护和机动是明显短板。",
            price = 1100,
            speed = 68f,
            hp = 5,
            reloadMs = 980,
            bulletSpeed = 455f,
            bulletPower = 3,
            penetration = 145,
            armorFront = 160,
            armorSide = 62,
            armorRear = 42,
            visionRange = 145f,
            scoutReveal = false,
            bodyColor = "#77715F",
            darkColor = "#38362F",
            trimColor = "#D6CEB5",
        ),
        VehicleSpec(
            id = VehicleId.PANTHER,
            faction = Faction.GERMAN,
            role = VehicleRole.MEDIUM,
            displayName = "黑豹A型坦克",
            shortName = "黑豹A型",
            history = "1943年研制的精锐中型坦克，拥有倾斜装甲和高穿透长炮，是柏林保卫战中德军的中坚力量，可与苏军IS-2正面抗衡。",
            price = 1400,
            speed = 102f,
            hp = 4,
            reloadMs = 720,
            bulletSpeed = 420f,
            bulletPower = 3,
            penetration = 130,
            armorFront = 110,
            armorSide = 52,
            armorRear = 38,
            visionRange = 162f,
            scoutReveal = false,
            bodyColor = "#8A7F60",
            darkColor = "#44402F",
            trimColor = "#E8DAA8",
        ),
        VehicleSpec(
            id = VehicleId.TIGER_II,
            faction = Faction.GERMAN,
            role = VehicleRole.HEAVY,
            displayName = "虎王重型坦克",
            shortName = "虎王",
            history = "二战德军最强重型坦克，正面装甲几乎无法被当时所有盟军火炮正面击穿，但极度笨重，机动性极差，燃料消耗惊人。",
            price = 1800,
            speed = 60f,
            hp = 7,
            reloadMs = 920,
            bulletSpeed = 470f,
            bulletPower = 4,
            penetration = 170,
            armorFront = 185,
            armorSide = 88,
            armorRear = 62,
            visionRange = 145f,
            scoutReveal = false,
            bodyColor = "#9C9478",
            darkColor = "#4A4738",
            trimColor = "#F0E8C0",
        ),
        VehicleSpec(
            id = VehicleId.T34_76,
            faction = Faction.SOVIET,
            role = VehicleRole.MEDIUM,
            displayName = "T-34/76 中型坦克",
            shortName = "T-34/76",
            history = "苏军装甲兵主力，机动优秀、车体低矮，适合侧翼突击和阵地反击。",
            price = 0,
            speed = 130f,
            hp = 3,
            reloadMs = 610,
            bulletSpeed = 335f,
            bulletPower = 2,
            penetration = 82,
            armorFront = 86,
            armorSide = 55,
            armorRear = 38,
            visionRange = 165f,
            scoutReveal = false,
            bodyColor = "#4F7A46",
            darkColor = "#263E24",
            trimColor = "#C9E5B3",
        ),
        VehicleSpec(
            id = VehicleId.T70,
            faction = Faction.SOVIET,
            role = VehicleRole.SCOUT,
            displayName = "T-70 轻型坦克",
            shortName = "T-70",
            history = "轻型侦察车辆，装甲和火力弱，但速度快、视野大，可揭示森林中的隐藏敌车。",
            price = 360,
            speed = 170f,
            hp = 2,
            reloadMs = 520,
            bulletSpeed = 315f,
            bulletPower = 1,
            penetration = 55,
            armorFront = 45,
            armorSide = 30,
            armorRear = 24,
            visionRange = 220f,
            scoutReveal = true,
            bodyColor = "#5EA653",
            darkColor = "#2C5A29",
            trimColor = "#DDF7C8",
        ),
        VehicleSpec(
            id = VehicleId.SU_152,
            faction = Faction.SOVIET,
            role = VehicleRole.ASSAULT_GUN,
            displayName = "SU-152 重型突击炮",
            shortName = "SU-152",
            history = "重型突击炮，装填慢但爆发极高，适合打击虎式和费迪南等重装甲目标。",
            price = 780,
            speed = 78f,
            hp = 4,
            reloadMs = 1080,
            bulletSpeed = 360f,
            bulletPower = 4,
            penetration = 118,
            armorFront = 112,
            armorSide = 62,
            armorRear = 42,
            visionRange = 140f,
            scoutReveal = false,
            bodyColor = "#5F6F4B",
            darkColor = "#2D3727",
            trimColor = "#D8E1B3",
        ),
        VehicleSpec(
            id = VehicleId.KV_1,
            faction = Faction.SOVIET,
            role = VehicleRole.HEAVY,
            displayName = "KV-1 重型坦克",
            shortName = "KV-1",
            history = "1941年让德军望而生畏的苏联重坦，莫斯科和斯大林格勒保卫战中支撑防线的铁壁；速度慢、机械可靠性差，但正面近乎不可穿透。",
            price = 1000,
            speed = 75f,
            hp = 5,
            reloadMs = 860,
            bulletSpeed = 340f,
            bulletPower = 2,
            penetration = 88,
            armorFront = 120,
            armorSide = 72,
            armorRear = 48,
            visionRange = 142f,
            scoutReveal = false,
            bodyColor = "#3A5E35",
            darkColor = "#1A2E18",
            trimColor = "#A8C8A0",
        ),
        VehicleSpec(
            id = VehicleId.T34_85,
            faction = Faction.SOVIET,
            role = VehicleRole.MEDIUM,
            displayName = "T-34/85 中型坦克",
            shortName = "T-34/85",
            history = "换装85mm炮后的T-34，具备压制虎式侧面的能力，是柏林战役苏军装甲主力，兼顾火力与机动。",
            price = 680,
            speed = 128f,
            hp = 3,
            reloadMs = 660,
            bulletSpeed = 365f,
            bulletPower = 3,
            penetration = 102,
            armorFront = 90,
            armorSide = 62,
            armorRear = 44,
            visionRange = 162f,
            scoutReveal = false,
            bodyColor = "#4A7240",
            darkColor = "#253D20",
            trimColor = "#C8E4B2",
        ),
        VehicleSpec(
            id = VehicleId.IS_2,
            faction = Faction.SOVIET,
            role = VehicleRole.HEAVY,
            displayName = "IS-2 重型坦克",
            shortName = "IS-2",
            history = "苏军最强重型坦克，122mm加农炮能在任何角度击穿虎式，是攻克柏林的铁拳。装填极慢，每次射击间隔都是高风险时间窗口。",
            price = 1600,
            speed = 82f,
            hp = 5,
            reloadMs = 1150,
            bulletSpeed = 395f,
            bulletPower = 5,
            penetration = 155,
            armorFront = 130,
            armorSide = 78,
            armorRear = 52,
            visionRange = 148f,
            scoutReveal = false,
            bodyColor = "#3E6838",
            darkColor = "#1E381C",
            trimColor = "#B8DCB0",
        ),
        VehicleSpec(
            id = VehicleId.CROMWELL,
            faction = Faction.BRITISH,
            role = VehicleRole.MEDIUM,
            displayName = "克伦威尔Mk.IV巡航坦克",
            shortName = "克伦威尔IV",
            history = "高速巡航坦克，诺曼底登陆后在法国战役中大量使用。速度是其最大优势，机动性超越大多数德军坦克，但装甲相对薄弱。",
            price = 0,
            speed = 148f,
            hp = 3,
            reloadMs = 580,
            bulletSpeed = 355f,
            bulletPower = 2,
            penetration = 92,
            armorFront = 76,
            armorSide = 52,
            armorRear = 36,
            visionRange = 170f,
            scoutReveal = false,
            bodyColor = "#5A6C45",
            darkColor = "#2C3622",
            trimColor = "#C2D89A",
        ),
        VehicleSpec(
            id = VehicleId.CHURCHILL,
            faction = Faction.BRITISH,
            role = VehicleRole.HEAVY,
            displayName = "丘吉尔Mk.IV步兵坦克",
            shortName = "丘吉尔IV",
            history = "英国重型步兵坦克，正面装甲极厚，越野能力出色，北非和意大利战役中为步兵提供近距离火力支援。",
            price = 1200,
            speed = 72f,
            hp = 5,
            reloadMs = 860,
            bulletSpeed = 335f,
            bulletPower = 3,
            penetration = 98,
            armorFront = 152,
            armorSide = 95,
            armorRear = 64,
            visionRange = 148f,
            scoutReveal = false,
            bodyColor = "#5B7050",
            darkColor = "#2C3B28",
            trimColor = "#C0D4B0",
        ),
        VehicleSpec(
            id = VehicleId.MATILDA_II,
            faction = Faction.BRITISH,
            role = VehicleRole.TANK_DESTROYER,
            displayName = "玛蒂尔达II步兵坦克",
            shortName = "玛蒂尔达II",
            history = "北非早期最强英军坦克，正面装甲让意大利和早期德军炮兵束手无策。速度极慢，容易被机动性强的敌方包抄。",
            price = 800,
            speed = 65f,
            hp = 4,
            reloadMs = 780,
            bulletSpeed = 310f,
            bulletPower = 2,
            penetration = 75,
            armorFront = 160,
            armorSide = 108,
            armorRear = 75,
            visionRange = 142f,
            scoutReveal = false,
            bodyColor = "#6A7A58",
            darkColor = "#33402A",
            trimColor = "#C8D8A8",
        ),
        VehicleSpec(
            id = VehicleId.FIREFLY,
            faction = Faction.BRITISH,
            role = VehicleRole.TANK_DESTROYER,
            displayName = "谢尔曼萤火虫坦克歼击车",
            shortName = "萤火虫",
            history = "英军将17磅反坦克炮装进谢尔曼底盘后的火力怪物，诺曼底后成为压制虎式与黑豹的关键车辆。",
            price = 1050,
            speed = 118f,
            hp = 3,
            reloadMs = 700,
            bulletSpeed = 420f,
            bulletPower = 3,
            penetration = 132,
            armorFront = 76,
            armorSide = 50,
            armorRear = 38,
            visionRange = 168f,
            scoutReveal = false,
            bodyColor = "#5E704E",
            darkColor = "#2E3826",
            trimColor = "#CAD8A6",
        ),
        VehicleSpec(
            id = VehicleId.COMET,
            faction = Faction.BRITISH,
            role = VehicleRole.MEDIUM,
            displayName = "彗星巡航坦克",
            shortName = "彗星",
            history = "战争末期英军最成熟的巡航坦克之一，兼具高速机动、可靠炮塔与强力77mm炮，是克伦威尔思想的完成形。",
            price = 1350,
            speed = 142f,
            hp = 3,
            reloadMs = 620,
            bulletSpeed = 395f,
            bulletPower = 3,
            penetration = 118,
            armorFront = 102,
            armorSide = 63,
            armorRear = 40,
            visionRange = 174f,
            scoutReveal = false,
            bodyColor = "#566842",
            darkColor = "#283421",
            trimColor = "#BFD498",
        ),
        VehicleSpec(
            id = VehicleId.VALENTINE,
            faction = Faction.BRITISH,
            role = VehicleRole.HEAVY,
            displayName = "瓦伦丁步兵坦克",
            shortName = "瓦伦丁",
            history = "结构紧凑、可靠耐用的英军步兵坦克，在北非与租借援苏战场都大量出现。低矮车体和稳固装甲适合防御推进。",
            price = 620,
            speed = 78f,
            hp = 4,
            reloadMs = 720,
            bulletSpeed = 315f,
            bulletPower = 2,
            penetration = 72,
            armorFront = 82,
            armorSide = 62,
            armorRear = 50,
            visionRange = 148f,
            scoutReveal = false,
            bodyColor = "#657654",
            darkColor = "#303C28",
            trimColor = "#C3D4A4",
        ),
        VehicleSpec(
            id = VehicleId.SHERMAN_M4,
            faction = Faction.AMERICAN,
            role = VehicleRole.MEDIUM,
            displayName = "M4谢尔曼中型坦克",
            shortName = "M4谢尔曼",
            history = "二战美军装甲主力，可靠性极高、产量庞大。正面对抗虎式处于劣势，但数量优势和快速补充能力无可比拟。",
            price = 0,
            speed = 122f,
            hp = 3,
            reloadMs = 600,
            bulletSpeed = 340f,
            bulletPower = 2,
            penetration = 85,
            armorFront = 76,
            armorSide = 50,
            armorRear = 38,
            visionRange = 162f,
            scoutReveal = false,
            bodyColor = "#5E7050",
            darkColor = "#2E3828",
            trimColor = "#C0D4A0",
        ),
        VehicleSpec(
            id = VehicleId.STUART,
            faction = Faction.AMERICAN,
            role = VehicleRole.SCOUT,
            displayName = "M3斯图亚特轻型坦克",
            shortName = "M3斯图亚特",
            history = "美军侦察轻坦，速度极快，可揭示敌方隐蔽目标；装甲和火力较弱，适合绕侧骚扰。",
            price = 380,
            speed = 180f,
            hp = 2,
            reloadMs = 500,
            bulletSpeed = 320f,
            bulletPower = 1,
            penetration = 52,
            armorFront = 44,
            armorSide = 28,
            armorRear = 22,
            visionRange = 228f,
            scoutReveal = true,
            bodyColor = "#6A8058",
            darkColor = "#334028",
            trimColor = "#D0E8B0",
        ),
        VehicleSpec(
            id = VehicleId.PERSHING,
            faction = Faction.AMERICAN,
            role = VehicleRole.HEAVY,
            displayName = "M26潘兴重型坦克",
            shortName = "M26潘兴",
            history = "美军应对德军重装甲而研制，1945年初投入欧洲战场，是美国首款能与黑豹和虎王正面抗衡的重型坦克。",
            price = 1500,
            speed = 95f,
            hp = 4,
            reloadMs = 780,
            bulletSpeed = 400f,
            bulletPower = 3,
            penetration = 128,
            armorFront = 102,
            armorSide = 76,
            armorRear = 50,
            visionRange = 155f,
            scoutReveal = false,
            bodyColor = "#607058",
            darkColor = "#30382A",
            trimColor = "#C8D8A8",
        ),
        VehicleSpec(
            id = VehicleId.SHERMAN_EASY_8,
            faction = Faction.AMERICAN,
            role = VehicleRole.MEDIUM,
            displayName = "M4A3E8谢尔曼中型坦克",
            shortName = "谢尔曼E8",
            history = "装备HVSS悬挂与76mm炮的后期谢尔曼，机动、装填与穿甲能力全面提升，是美军在欧洲后期最可靠的主力中型坦克。",
            price = 900,
            speed = 134f,
            hp = 3,
            reloadMs = 570,
            bulletSpeed = 370f,
            bulletPower = 3,
            penetration = 105,
            armorFront = 83,
            armorSide = 50,
            armorRear = 38,
            visionRange = 166f,
            scoutReveal = false,
            bodyColor = "#5E7250",
            darkColor = "#2D3826",
            trimColor = "#C2D69F",
        ),
        VehicleSpec(
            id = VehicleId.M10_WOLVERINE,
            faction = Faction.AMERICAN,
            role = VehicleRole.TANK_DESTROYER,
            displayName = "M10狼獾坦克歼击车",
            shortName = "M10狼獾",
            history = "基于谢尔曼底盘的美军坦克歼击车，开放式炮塔视野良好，3英寸炮足以威胁多数德军坦克，但防护薄弱。",
            price = 880,
            speed = 126f,
            hp = 3,
            reloadMs = 690,
            bulletSpeed = 405f,
            bulletPower = 3,
            penetration = 122,
            armorFront = 57,
            armorSide = 25,
            armorRear = 25,
            visionRange = 188f,
            scoutReveal = false,
            bodyColor = "#596C4E",
            darkColor = "#293425",
            trimColor = "#BCCF9E",
        ),
        VehicleSpec(
            id = VehicleId.M18_HELLCAT,
            faction = Faction.AMERICAN,
            role = VehicleRole.TANK_DESTROYER,
            displayName = "M18地狱猫坦克歼击车",
            shortName = "M18地狱猫",
            history = "二战中速度极高的美军坦克歼击车，依靠高速转场和侧翼伏击取胜。装甲极薄，正面对炮几乎没有容错。",
            price = 950,
            speed = 185f,
            hp = 2,
            reloadMs = 650,
            bulletSpeed = 410f,
            bulletPower = 3,
            penetration = 120,
            armorFront = 38,
            armorSide = 20,
            armorRear = 20,
            visionRange = 204f,
            scoutReveal = true,
            bodyColor = "#61754E",
            darkColor = "#2C3924",
            trimColor = "#C4D89E",
        ),
    )

    private val byId: Map<VehicleId, VehicleSpec> = all.associateBy(VehicleSpec::id)

    fun get(id: VehicleId): VehicleSpec = requireNotNull(byId[id]) { "Unknown vehicle id: $id" }

    fun forFaction(faction: Faction): List<VehicleSpec> = all.filter { it.faction == faction }

    fun defaultForFaction(faction: Faction): VehicleId = when (faction) {
        Faction.GERMAN -> VehicleId.PZ_IV_H
        Faction.SOVIET -> VehicleId.T34_76
        Faction.BRITISH -> VehicleId.CROMWELL
        Faction.AMERICAN -> VehicleId.SHERMAN_M4
    }
}
